// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP_h3fcP1K6XS21H2TLztBs2IXANLqVQ0',
    appId: '1:583924063249:web:3d06550fdd82c98e6365b0',
    messagingSenderId: '583924063249',
    projectId: 'parisportif-b983c',
    authDomain: 'parisportif-b983c.firebaseapp.com',
    storageBucket: 'parisportif-b983c.firebasestorage.app',
    measurementId: 'G-80485QYCJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFgmJ_g3H3eW6-1gSh_2wSnOmTnFzz4ko',
    appId: '1:583924063249:android:f1c5139ab65f18166365b0',
    messagingSenderId: '583924063249',
    projectId: 'parisportif-b983c',
    storageBucket: 'parisportif-b983c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqXImKlEWQcSmhNWMLsz9liswBQvOug0',
    appId: '1:583924063249:ios:de912ee206e3485e6365b0',
    messagingSenderId: '583924063249',
    projectId: 'parisportif-b983c',
    storageBucket: 'parisportif-b983c.firebasestorage.app',
    iosBundleId: 'com.example.pari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjqXImKlEWQcSmhNWMLsz9liswBQvOug0',
    appId: '1:583924063249:ios:de912ee206e3485e6365b0',
    messagingSenderId: '583924063249',
    projectId: 'parisportif-b983c',
    storageBucket: 'parisportif-b983c.firebasestorage.app',
    iosBundleId: 'com.example.pari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP_h3fcP1K6XS21H2TLztBs2IXANLqVQ0',
    appId: '1:583924063249:web:394b2d29bd0f1d0c6365b0',
    messagingSenderId: '583924063249',
    projectId: 'parisportif-b983c',
    authDomain: 'parisportif-b983c.firebaseapp.com',
    storageBucket: 'parisportif-b983c.firebasestorage.app',
    measurementId: 'G-6QJCZQW1Z4',
  );
}
